### ISSUE TITLE
x64 library inst ad x86

### ISSUE THREAD

**Issue by ilyapashuk** [dkager/tolk#14]
helo

I downloaded your last build from link of top of the readme and found that tolk.dll library placed in x86 directory is for x64 cpu

**Comment by ndarilek** [comment]
Ah, should have checked this first. I hit the exact same issue. I'm not a Windows developer and fought with this for quite a while.

Are the *other* DLLs in the directory 32-bit? Does anyone have a 32-bit DLL they could share?

Thanks.

**Comment by dkager** [comment]
Well well... My fault, it's all fixed now.

**Comment by ndarilek** [comment]
Thanks, much appreciated!
