### ISSUE TITLE
.net wrapper errors

### ISSUE THREAD

**Issue by Westernstandard** [dkager/tolk#2]
Created a small project to test in .net 4.0. Called Tolk.Load(); Tolk.Output("some text"); and failed with: A call to PInvoke function 'TolkDotNet!DavyKager.Tolk::Tolk_Output' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.

**Comment by dkager** [comment]
32-bit or 64-bit framework? Does this also happen with `examples/c#/ConsoleApp.cs` (or the VB.net equivalent)?

**Comment by dkager** [comment]
Should be fixed with today's commits.

**Comment by Westernstandard** [comment]
Thank you so much! My wife just had a baby, so I’ll take a look in a few days.

 

The feature mentioned with regards to x86/x64 capabilities, would be similar to those found in SqlLite wherein the .net wrapper looks in a sub folder (x86 or x64) for the .dll appropriate for the build detected by the wrapper, which itself operates in Any CPU mode.

 

Regards,

 

Richard Tregaskis 
Western Standard Technical Support 
Ph: 801-224-7404 
Fx: 801-224-8909

**Comment by dkager** [comment]
Congratulations! :)
Thanks for the other remark regarding x86/x64. This also applies to Java and probably others too. Will look into it.

Feel free to post your results with the updated .NET wrapper whenever time permits. I don't work with .NET myself, so any feedback is appreciated.

**Comment by Westernstandard** [comment]
Hi Mr. Kager,

 

Thank you for updating the .dll. It appears to be working now. I had a couple of quick questions for you whenever you get time:

1.       Is it necessary to load/unload the library between each call, or could I Tolk.Load with the application and Tolk.Unload when closing? Would there be a process or memory leak?

2.       I don’t know C or CPP hardly at all – how hard would it be to implement something like this in the Tolk.dll?:

3.    #ifdef _WIN64

4.           if (file_exists("nvdaControllerClient64.dll"))

5.                controller(LoadLibrary(L"nvdaControllerClient64.dll")),

6.           else

7.                controller(LoadLibrary(L"x64\\nvdaControllerClient64.dll")),

8.    #else

9.           if (file_exists("nvdaControllerClient32.dll"))

10.               controller(LoadLibrary(L"nvdaControllerClient32.dll")),

11.          else

12.               controller(LoadLibrary(L"x86\\nvdaControllerClient32.dll")),

13.   #endif

 

I’ve updated your C# wrapper to would allow me to tap the x86 or x64 subdirectory of my application for the dll, depending on the operating environment, but the tolk.dll itself is then unable to access the screenreader libraries in that relative path (e.g. NVDA is not detected when it is running). If the Tolk.dll could check a subdirectory for the screenreader libraries, then my wrapper could accommodate the Tolk.dll being either the same path as the executable, or a subdirectory (x86 and x64).

 

3. What is the difference between Output and Speak? I wasn’t really clear from everything I read. Will either one accept RTF?

 

 

Regards,

 

Richard Tregaskis 
Western Standard Technical Support 
Ph: 801-224-7404 
Fx: 801-224-8909

**Comment by Westernstandard** [comment]
HI Davy,

 

Please disregard the request to modify the dll. I’ve been able to modify the .net wrapper to include a search path (attached).

 

Regards,

 

Richard Tregaskis 
Western Standard Technical Support 
Ph: 801-224-7404 
Fx: 801-224-8909

**Comment by dkager** [comment]
> Is it necessary to load/unload the library between each call, ...
No. In fact, you should usually `Load` only once (before you need the library, maybe at start-up) and also `Unload` only once.

> What is the difference between Output and Speak? ... Will either one accept RTF?
The difference is that `Output` is a best-effort method that uses whatever the screen reader supports, i.e. speech and braille, only speech or only braille. On the other hand, `Speak` tries only to speak the text. Its counterpart is the `Braille` method.

I think a method to set the search path for screen reader DLLs makes sense. Using hard-coded directory names isn't the solution because there will no doubt be a use case for a different directory structure. As for Tolk itself, you can definitely extend and alter the wrapper. I meant them as starting points anyway (and to be fair, also as programming exercises for myself).

Thanks!
