### ISSUE TITLE
change the license from LGPL if is it possible

### ISSUE THREAD

**Issue by brightening-eyes** [dkager/tolk#3]
hi,
as you know, gnu licenses has some restrictions, witch is not good at all
one of them is disallow the programmers to use static libraries and forces them to link the shared libraries
i recommend you to change the LGPL to zlib/PNG or BSL-1.0 or MIT or something similar (permissive license) if it is possible
thanks in advance

**Comment by dkager** [comment]
> gnu licenses has some restrictions, witch is not good at all
A bit biased perhaps.

> one of them is disallow the programmers to use static libraries and forces them to link the shared libraries
No, you are required to provide a way for users to modify the library and use that modified version in your software. Using DLLs is but one way to achieve this.

> i recommend you to change the LGPL to zlib/PNG or BSL-1.0 or MIT or something similar
Sorry, no. Using the LGPL was a conscious decision.
