### ISSUE TITLE
compiling tolk with MinGW and a code::blocks project file

### ISSUE THREAD

**Issue by brightening-eyes** [dkager/tolk#6]
hello,
i've compiled tolk with codeblocks and MinGW-w64, with a change and a project file:
in ScreenReaderDriverSapi.h, before `#include <sapi.h>` i've added `#include <windows.h>`
it fixed some errors in mbsystem.h such as type definitions, etc
and, this is the code for the codeblocks project file:
`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<CodeBlocks_project_file>
    <FileVersion major="1" minor="6" />
    <Project>
        <Option title="tolk" />
        <Option pch_mode="2" />
        <Option compiler="gcc" />
        <Build>
            <Target title="Debug">
                <Option output="bin/Debug/tolk" prefix_auto="1" extension_auto="1" />
                <Option object_output="obj/Debug/" />
                <Option type="3" />
                <Option compiler="gcc" />
                <Option createDefFile="1" />
                <Option createStaticLib="1" />
                <Compiler>
                    <Add option="-Wall" />
                    <Add option="-g" />
                </Compiler>
                <Linker>
                    <Add library="user32" />
                </Linker>
            </Target>
            <Target title="Release">
                <Option output="bin/Release/tolk" prefix_auto="1" extension_auto="1" />
                <Option object_output="obj/Release/" />
                <Option type="3" />
                <Option compiler="gcc" />
                <Option createDefFile="1" />
                <Option createStaticLib="1" />
                <Compiler>
                    <Add option="-O2" />
                    <Add option="-Wall" />
                </Compiler>
                <Linker>
                    <Add option="-s" />
                    <Add library="user32" />
                </Linker>
            </Target>
        </Build>
        <Compiler>
            <Add option="-std=c++14" />
            <Add option="-DUNICODE=1" />
            <Add option="-D_EXPORTING=1" />
        </Compiler>
        <Linker>
            <Add library="advapi32" />
            <Add library="ole32" />
            <Add library="oleaut32" />
            <Add library="user32" />
            <Add library="kernel32" />
            <Add library="sapi" />
        </Linker>
        <Unit filename="src/ScreenReaderDriver.h" />
        <Unit filename="src/ScreenReaderDriverJAWS.cpp" />
        <Unit filename="src/ScreenReaderDriverJAWS.h" />
        <Unit filename="src/ScreenReaderDriverNVDA.cpp" />
        <Unit filename="src/ScreenReaderDriverNVDA.h" />
        <Unit filename="src/ScreenReaderDriverSA.cpp" />
        <Unit filename="src/ScreenReaderDriverSA.h" />
        <Unit filename="src/ScreenReaderDriverSAPI.cpp" />
        <Unit filename="src/ScreenReaderDriverSAPI.h" />
        <Unit filename="src/ScreenReaderDriverSNova.cpp" />
        <Unit filename="src/ScreenReaderDriverSNova.h" />
        <Unit filename="src/ScreenReaderDriverWE.cpp" />
        <Unit filename="src/ScreenReaderDriverWE.h" />
        <Unit filename="src/ScreenReaderDriverZT.cpp" />
        <Unit filename="src/ScreenReaderDriverZT.h" />
        <Unit filename="src/Tolk.cpp" />
        <Unit filename="src/Tolk.h" />
        <Unit filename="src/Tolk.rc">
            <Option compilerVar="WINDRES" />
        </Unit>
        <Unit filename="src/TolkVersion.h" />
        <Unit filename="src/fsapi.c">
            <Option compilerVar="CC" />
        </Unit>
        <Unit filename="src/fsapi.h" />
        <Unit filename="src/wineyes.c">
            <Option compilerVar="CC" />
        </Unit>
        <Unit filename="src/wineyes.h" />
        <Unit filename="src/zt.c">
            <Option compilerVar="CC" />
        </Unit>
        <Unit filename="src/zt.h" />
        <Extensions>
            <code_completion />
            <envvars />
            <debugger />
            <lib_finder disable_auto="1" />
        </Extensions>
    </Project>
</CodeBlocks_project_file>
`
i couldn't upload that project file because github didn't allow this type of file to be uploaded
thanks

**Comment by dkager** [comment]
> in ScreenReaderDriverSapi.h, before  #include <sapi.h>  i've added  #include <windows.h> 

This is apparently already done in `sapi.h`:

```
#ifndef COM_NO_WINDOWS_H
#include "windows.h"
#include "ole2.h"
#endif /*COM_NO_WINDOWS_H*/
```

For the XML file, please open a PR if this is still relevant.
