### ISSUE TITLE
Example C# ConsoleApp does not detect running NVDA

### ISSUE THREAD

**Issue by Weqqen** [dkager/tolk#9]
Hi,
I was trying to connect my C# (win 7 64bit) application to any synthesizer but more or less it failed. Then my friend told me about Tolk - so I tried this. And another issue emerged:
1) Nvda is running (and talking wherever I move cursor ;) ), version 2017.3
2) I run \tolk\examples\c#\ConsoleApp.exe (tolk.dll is in the same directory)
3) The output shows that:
```
Tolk -- C# Console App Example
Initializing Tolk...
Querying for the active screen reader driver...
None of the supported screen readers is running
Let's output some text...
Failed to output text
Finalizing Tolk...
Done!
```

4) Moreover it does not fallback to SAPI (I assume that it means, the text will be read by system speech synthesizer, which is available, however is not reading everything wherever I point)

Thanks for the help
Weqqen

PS Btw - when I was experimenting with System.Speech.Internal.Synthesis.VoiceSynthesis.Speak I encountered other problem: when I choose voice other than Anna I got Exception "value cannot be null" like in https://stackoverflow.com/questions/22057049/application-exit-on-synthesizer-speak-system-speech-dll-non-microsoft-voices just after use .Speak() method. Have you maybe encountered this issue in your career?

**Comment by dkager** [comment]
As for (2): make sure `nvdaControllerClient32.dll` or `nvdaControllerClient64.dll` is also in the same directory as `Tolk.dll`.

As for (4): SAPI is disabled by default, see the readme.

**Comment by Weqqen** [comment]
Hi - copying nvdaConctrollerClient was enough, to make it work.
Thanks!,
GN
